services:
  - type: web
    name: wanderlust-travel-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    domains:
      - wanderlust-travel-app.onrender.com
